name: sandbox_purity
description: A sample purity application
dependencies:
  browser: any
  bson: any
  controls_and_panels: any
  http: any
  purity: '>=0.9.0 <0.10.0'
  purity_oauth2: '>=0.1.0 <0.2.0'
  route: any
dev_dependencies:
  unittest: any
