name: sandbox_purity
description: A sample purity application
dependencies:
  browser: any
  bson: any
  controls_and_panels: any
  http: any
  oauth2: '>=0.9.2 <1.0.0'
  purity:
    path: ../purity
  route: any
dev_dependencies:
  unittest: any
