name: sandbox_purity
description: A sample purity application
dependencies:
  browser: any
  bson: any
  controls_and_panels: any
  oauth2: '>=0.9.2 <1.0.0'
  purity: '>=0.8.6 <0.9.0'
dev_dependencies:
  unittest: any
